#FROM mcr.microsoft.com/dotnet/sdk:8.0 as build
#WORKDIR /app
#COPY . .
#WORKDIR /app
#RUN dotnet publish -c Release -o /app/publish
#
#FROM mcr.microsoft.com/dotnet/aspnet:8.0 as final
#WORKDIR /app
#COPY --from=build /app/publish .
#ENTRYPOINT ["dotnet", "ProjectAPI.dll"]

